import re
from pydantic import BaseModel, Field
from typing import Optional

class Service(BaseModel):
    
    id: Optional[str] = Field(
        default= None,
        description="ID generated by mongodb"
    )
    
    name: str = Field(
        description="Nombre del servicio",
        min_length=1,
        max_lenght= 100,
    )
    
    description: str = Field(
        description="Que es lo que hace el servicio",
         min_length=1,
        max_lenght= 100,
    )
    
    price: float = Field(
        description="Costo del servicio",
        gt=0
    )