import re
from pydantic import BaseModel, Field
from typing import Optional

class State(BaseModel):
    
    id: Optional[str] = Field(
        default= None,
        description="ID generated by mongodb"
    )
    
    name: str = Field(
        description="Name of the State",
        pattern=r"^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ' -]+$",
        examples=["Ordered", "In Process", "Ready", "Payed", "Cancelled"]
    )
    
    active: bool = Field(
        description="The state is active",
        default=True,
    )
