import re
from pydantic import BaseModel, Field
from typing import Optional

class Order(BaseModel):
    
    id: Optional[str] = Field(
        default= None,
        description="ID generated by mongodb"
    )
    
    appointment_id: Optional[str] = Field(
        default=None,
        description="ID generated"
    )
    
    subtotal: float = Field(
        description="Subtotal of the order",
        gt=0
    )
    
    taxes: Optional[float] = Field(
        description="Descuento aplicado a la orden",
        default=0.0,
        ge=0
    )
    
    total: Optional[float]= Field(
        description="Total de la orden (subtotal + taxes)",
        default=0.0,
        gt=0
    )
    
