import re
from pydantic import BaseModel, Field
from typing import Optional

class InventoryType(BaseModel):
    
    id: Optional[str] = Field(
        default= None,
        description="ID generated by mongodb"
    )
    name: str = Field(
        description="Name of the Inventory Type",
        pattern=r"^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ' -]+$",
    )
    
    active: Optional[bool] = Field(
        description="The state is active",
        default=True,
    )