from datetime import datetime
import re
from pydantic import BaseModel, Field
from typing import Optional

class Inventory(BaseModel):
    
    id: Optional[str] = Field(
        default= None,
        description="ID generated by mongodb"
    )

    id_inventory_type: str = Field(
        description="ID del tipo de catálogo al que pertenece",
        examples=["507f1f77bcf86cd799439011"]
    )
    
    name: str = Field(
        description="Name of the State",
        pattern=r"^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ' -]+$",
        examples=["Ordered", "In Process", "Ready", "Payed", "Cancelled"]
    )

    creation_date: Optional[datetime] = Field(
        default=None,
        description="Creation datetime; server sets it on create"
    )
    
    active: bool = Field(
        description="The state is active",
        default=True,
    )